# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos-vb-1.0"

  config.vm.synced_folder "mount", "/mnt"

  # define master node
  config.vm.define "centos-master" do |master|
    master.vm.hostname = "centos-master"
    master.vm.network "private_network", ip: "192.168.2.2"
  end

  # define worker nodes IP range 192.168.10.x
  (2..255).each do |i|
    config.vm.define "centos-node-#{i}" do |node|

        node.vm.hostname = "centos-node-#{i}"

        node.vm.network "private_network", ip: "192.168.10.#{i}"
    end
  end

  # define worker nodes IP range 192.168.20.x
  (257..510).each do |j|
    config.vm.define "centos-node-#{j}" do |node2|
        node2.vm.hostname = "centos-node-#{j}"
        node2.vm.network "private_network", ip: "192.168.20.#{j-255}"
    end
  end

  # more worker nodes can be defined

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
#   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
 #    vb.gui = false
  #   vb.cpus = 2
     # Customize the amount of memory on the VM:
   #  vb.memory = "1024"
  # end

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL

    sudo yum -y install kernel-uek-devel
    sudo yum -y update

     cat /mnt/node.pub >> /home/vagrant/.ssh/authorized_keys
     echo "StrictHostKeyChecking no" >> /home/vagrant/.ssh/config
     echo "IdentityFile /home/vagrant/node" >> /home/vagrant/.ssh/config
     sudo service ssh restart
     cp /mnt/* /home/vagrant/
     sudo chmod 777 node

     #chmod u+x /home/vagrant/mpi-install.sh
     #/home/vagrant/mpi-install.sh
  SHELL
end
