# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

## Vagrantfile for ubuntu-desktop-20.04

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ajcohen125/ubuntu-server-20.04"

  config.vm.synced_folder "mount", "/mnt"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  # define master node
  config.vm.define "ubuntu-server-20.04-master" do |master|
    master.vm.hostname = "ubuntu-sv-20-master"
    master.vm.network "private_network", ip: "192.168.2.20", name: "vboxnet0", netmask: "255.255.0.0"
  end

  # define worker nodes IP range 192.168.10.x
  (1..255).each do |i|
    config.vm.define "ubuntu-server-20.04-node-#{i}" do |node|

        node.vm.hostname = "ubuntu-sv-20-node-#{i}"

        node.vm.network "private_network", ip: "192.168.20.#{i}", name: "vboxnet0", netmask: "255.255.0.0"
    end
  end

  # define worker nodes IP range 192.168.20.x
  #(257..510).each do |j|
  #  config.vm.define "centos-node-#{j}" do |node2|
  #      node2.vm.hostname = "centos-node-#{j}"
  #      node2.vm.network "private_network", ip: "192.168.20.#{j-255}"
  #  end
  #end

  # more worker nodes can be defined

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
#   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
 #    vb.gui = false
  #   vb.cpus = 2
     # Customize the amount of memory on the VM:
   #  vb.memory = "1024"
  # end

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL

    sudo apt -y update

     cp /mnt/* /home/vagrant/

     chmod u+x /home/vagrant/vm-setup.sh
     /home/vagrant/vm-setup.sh

    sudo ip route add default via 192.168.2.1 dev enp0s8
  SHELL
end
